### PR TITLE
Config block styling & text selection fixes

### LINKED ISSUE #14040: Documentation's new theme may be causing errors.
## The problem

The default `payload_on` and `payload_off` for an MQTT Binary Sensor are _uppercase_ `ON` and `OFF`. However, the new documentation theme appears to be forcing certain text into _lowercase_. As a result, it now shows that the **default states** are `on` and `off`.

Screenshot from 2020-07-19 11-37-17

So is the theme causing documentation errors or is there an upcoming breaking change to re-define the default payload values?

NOTE
The documentation may contain other instances of text forced to lowercase. I have mentioned the example of MQTT Binary Sensor because that's the first instance of the error I noticed.

### LINKED ISSUE #14414: Cannot copy name of configuration variables without pain
## The problem

This may be multiple different issues, but both preventing the same action. I reproduced both errors in Firefox 80.0 and Chromium 83.0.4103.116 (if not stated otherwise) on Debian Unstable (using X11 as backend) without page modifying add-ons. I found the issues originally on https://www.home-assistant.io/lovelace/history-graph/, but could reproduce the issue on multiple other pages and due to the consistent design, this may happen on all pages.

It is about the theming of the "configuration variables" / "options for entities" / ... tables. There I tried to first select a name of one variable and then copy the variable / option name. I failed to select the name due to multiple small design flaws (as I think off):
1. Every name has a anchor icon left of it when hovering over the name (which is great per se), but it's clickable area does overlap a large part of the name (e.g. the first three characters of `type`) preventing me to double-click the name to let the browser automatically only select the word I wish to select.
2. Also due to the anchor, it is not possible to begin selecting the word from the left to the right using the mouse.
3. (*Firefox only*) Selecting the word from the right to the left also seems impossible also due to the anchor overlapping a significant part of the name. Chromium seems to continue selecting texts below other elements (z-axis), but Firefox doesn't, maybe thinking that the text is not visible to the user so it does not need to be selectable.
4. When trying to prevent clicking on the anchor works (e.g. on longer names like `hours_to_show`) and using a double-click, both browsers always (in my testcases) select the name **and** its type, see:
  Screenshot_20200906_195215
  On other examples it may also include the `REQUIRED` marker:
  image
  A triple-click does select the whole "line" if not already done, which is expected:
  image
  This does happen because the website uses a padding to separate these words and so does not separate these words in a logical way like when using a common whitespace character (e.g. ` `), a grid, a flexbox, or using `display: inline-block` on the span. Then the browsers can detect that each item (name, type, …) are each a single entity.

It would be great if these could be fixed to improve the user experience while using the documentation.

### PR DESCRIPTION
**Pull request by frenck**
## Proposed change

This PR addresses 2 issues reported with our configuration blocks.

- Default values are text transformed to lower case. In some cases (like MQTT), this is not wished for, as the value should be `ON` not `on`. This text transformation has been removed from the default value. (#14040)

- Variable names in configuration blocks are hard to select/copy. A little old trick has been added to this PR to add spaces around the config variable name in the HTML. When double clicking, Chrome will now select just the config var. (#14414)

image

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #14040 fixes #14414

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by balloob — DISMISSED** [review]

File: plugins/configuration.rb [hunk 1]
```diff
@@ -61,7 +61,7 @@ def render_config_vars(vars:, component:, platform:, converter:, classes: nil, p
 
       result << vars.map do |key, attr|
         markup = Array.new
-        markup << "<div class='config-vars-item'><div class='config-vars-label'><a name='#{slug(key)}' class='title-link' href='\##{slug(key)}'></a> <span class='config-vars-label-name'>#{key}</span>"
+        markup << "<div class='config-vars-item'><div class='config-vars-label'><a name='#{slug(key)}' class='title-link' href='\##{slug(key)}'></a> <span class='config-vars-label-name'> #{key} </span>"
```
Comment (balloob) [inline plugins/configuration.rb:65]: Should we add a comment?

Comment (frenck) [reply plugins/configuration.rb:65]: Done 👍
