### PR TITLE
Fix links to device class and customizing entities

### LINKED ISSUE #32480: device_class information missing
### Feedback

There are links in the documentation to https://www.home-assistant.io/docs/configuration/customizing-devices/#device-class (e.g. from https://www.home-assistant.io/docs/blueprint/selectors/#device_class) but there's absolutely nothing about device classes on this page.

### URL

https://www.home-assistant.io/docs/configuration/customizing-devices/

### Version

2024.4.4

### Additional information

(Semi-unrelated rant: It really feels like someone purged all information on what to use for values in the yaml from the documentation. On the one hand, the UI kicks you into yaml every time you want to do anything more complicated than "press button, turn on light", on the other hand, the documentation does its best to not give you anything but "click here, click there".)

### PR DESCRIPTION
**Pull request by c0ffeeca7**
## Proposed change

Fix links to device class and customizing entities
- add redirect
- addresses issue raised in #32480

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #32480

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

File: source/_redirects [hunk 1]
```diff
@@ -263,6 +263,8 @@ layout: null
 /draw_assist /voice_control/s3-box-customize/#to-draw-your-own-images
 /projects/thirteen-usd-voice-remote/ /voice_control/thirteen-usd-voice-remote/
 /docs/backend/updater /integrations/analytics
+docs/configuration/customizing-devices/#device-class /integrations/homeassistant/#device-class
+docs/configuration/customizing-devices/#customizing-entities /integrations/homeassistant/#editing-the-entity-settings-in-yaml
```
Comment (ludeeus) [inline source/_redirects]:
```suggestion
/docs/configuration/customizing-devices/#device-class /integrations/homeassistant/#device-class
/docs/configuration/customizing-devices/#customizing-entities /integrations/homeassistant/#editing-the-entity-settings-in-yaml
```

File: plugins/configuration.rb [hunk 2]
```diff
@@ -2,7 +2,7 @@ module Jekyll
   class ConfigurationBlock < Liquid::Block
     TYPE_LINKS = {
       'action'       => '/docs/scripts/',
-      'device_class' => '/docs/configuration/customizing-devices/#device-class',
+      'device_class' => '/integrations/homeassistant/#device-class',
       'template'     => '/docs/configuration/templating/',
       'icon'         => '/docs/configuration/customizing-devices/#icon',
```
Comment (ludeeus) [inline plugins/configuration.rb]:
```suggestion
      'icon'         => /integrations/homeassistant/#icon',
```
This one Im not sure about, an "Icon" section could be added to the current page?

**Review by ludeeus — DISMISSED** [review]

File: plugins/configuration.rb [hunk 3]
```diff
@@ -2,9 +2,9 @@ module Jekyll
   class ConfigurationBlock < Liquid::Block
     TYPE_LINKS = {
       'action'       => '/docs/scripts/',
-      'device_class' => '/docs/configuration/customizing-devices/#device-class',
+      'device_class' => '/integrations/homeassistant/#device-class',
       'template'     => '/docs/configuration/templating/',
-      'icon'         => '/docs/configuration/customizing-devices/#icon',
+      'icon'         => /integrations/homeassistant/#icon',
```
Comment (ludeeus) [inline plugins/configuration.rb]:
```suggestion
      'icon'         => '/integrations/homeassistant/#icon',
```

**Review by ludeeus — APPROVED** [review]
